import type { NextPage } from 'next'
import { useEffect, useRef, MutableRefObject } from 'react'
import BigNumber from 'bignumber.js';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { encodeURL, createQR } from '@solana/pay'
import { PublicKey } from '@solana/web3.js'

type Props = {
	recipient: PublicKey;
    amount: BigNumber;
    reference?: PublicKey;
	label: string;
    message: string;
    memo: string;
	splToken?: PublicKey;
}

async function generateQRCode (props: Props) {
	const url = encodeURL(props);
	console.log(url)
	const qrCode = createQR(url);
	return qrCode;
}


const Home: NextPage = () => {
	const qrRef = useRef() as MutableRefObject<HTMLInputElement>;

	useEffect(() => {
		(async () => {
			const data = {
				recipient: new PublicKey('8kgbAgt8oedfprQ9LWekUh6rbY264Nv75eunHPpkbYGX'),
				amount: new BigNumber(1),
				label: 'Test',
				message: 'Test',
				memo: 'Test'
			}
			const qrCode = await generateQRCode(data);
			qrCode.append(qrRef.current)
		})();
	}, [])

	return (
		<div className={styles.container}>
			<Head>
				<title>@solana/pay bug example</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js </a>
					@solana/pay bug example!
				</h1>
				<div ref={qrRef} />
			</main>
		</div>
	)
}

export default Home
